#!/usr/bin/env bash
# Render packaging/homebrew/mollow.rb for a release.
# Usage: ./packaging/render-homebrew-formula.sh <version> <sha_arm64> <sha_x86_64_darwin> <sha_linux> [output]
set -euo pipefail

VERSION="${1:?usage: $0 <version> <sha_arm64> <sha_x86_64_darwin> <sha_linux> [output]}"
SHA_ARM64="${2:?missing sha256 for aarch64-apple-darwin}"
SHA_X86_64_DARWIN="${3:?missing sha256 for x86_64-apple-darwin}"
SHA_LINUX="${4:?missing sha256 for x86_64-unknown-linux-gnu}"
OUTPUT="${5:-packaging/homebrew/mollow.rb}"
REPO="${MOLLOW_REPO:-ingeniousfrog/Mollow}"
BASE="https://github.com/${REPO}/releases/download/v${VERSION}"

mkdir -p "$(dirname "${OUTPUT}")"
cat >"${OUTPUT}" <<EOF
# Homebrew formula for Mollow (CLI).
# Publish this file in: github.com/ingeniousfrog/homebrew-tap/Formula/mollow.rb
# Regenerated by packaging/render-homebrew-formula.sh (see docs/homebrew.md).

class Mollow < Formula
  desc "Cross-platform machine inspection and performance-baseline CLI"
  homepage "https://github.com/ingeniousfrog/Mollow"
  license "Apache-2.0"
  version "${VERSION}"

  on_macos do
    on_arm do
      url "${BASE}/mollow-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_ARM64}"
    end
    on_intel do
      url "${BASE}/mollow-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_X86_64_DARWIN}"
    end
  end

  on_linux do
    url "${BASE}/mollow-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "${SHA_LINUX}"
  end

  def install
    bin.install "mollow"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mollow --version")
    assert_match "inspect", shell_output("#{bin}/mollow --help")
  end
end
EOF

echo "Wrote ${OUTPUT} for v${VERSION}"
